import Extra.Equiv.Basic
import Extra.Equiv.Fun
import Extra.Equiv.List
import Extra.Equiv.Option
import Extra.Equiv.Prod
import Extra.Equiv.Quotient
import Extra.Equiv.Sigma
import Extra.Equiv.Subtype
import Extra.Equiv.Sum
